### ISSUE TITLE
Bulma is great!

### ISSUE THREAD

**Issue by spadino** [joshuajansen/bulma-rails#15]
Hi! I'm currently considering Bulma as a strong candidate for my next project. I'm relative new to sass, so I would like to know which is the preferred method to use to compile Bulma, after 'npm install bulma'.

Congratulations, I'm delighted with what I saw till now...

**Comment by joshuajansen** [comment]
Hi @andreaspada, I'm not the creator of Bulma, this repository is specifically meant for using Bulma in a Ruby on Rails application. If you're using Rails too, you should follow the steps in the readme of this repo (https://github.com/joshuajansen/bulma-rails)

If not, take a look at the general documentation on the official Bulma website:  http://bulma.io/documentation/overview/start/ 

Good luck!
