### ISSUE TITLE
Update to 4.2?

### ISSUE THREAD

**Issue by paulkmiller** [joshuajansen/bulma-rails#16]
Any thoughts on updating to the latest build of Bulma? If there aren't any immediate plans I may start working on the update on my off-time to contribute.

**Comment by himanish-k** [comment]
I'm waiting on the update too. Would appreciate an update since a lot of bug fixes have happened since 0.4.1 .

**Comment by joshuajansen** [comment]
Hi @paulkmiller and @himanish-k, I've updated the gem to use the assets from Bulma 0.4.2 but definitely feel free to create a PR next time 😄

**Comment by paulkmiller** [comment]
Thanks @joshuajansen, you're the best!
