### ISSUE TITLE
Data.today in gemspec gives bundler errors

### ISSUE THREAD

**Issue by Leonas** [joshuajansen/bulma-rails#18]
I think this line is giving me errors:
```
 gem.date = Date.today
```
It results in:

There was an error while loading `bulma-rails.gemspec`: uninitialized constant Date

I think this should be the release day of the gem version.

**Comment by Leonas** [comment]
Removing the gem.date line also worked so I created a pull request with it removed since it wasn't really being used anyway.

**Comment by joshuajansen** [comment]
Interesting find @Leonas :) `date` doesn't even seem to be a supported attribute anymore. Thanks for creating the PR!
