### ISSUE TITLE
Undefined variable: "$body-background"

### ISSUE THREAD

**Issue by alfiehub** [joshuajansen/bulma-rails#20]
I've followed the steps described in the README and added `@import "bulma";` to `application.scss`, but I'm receiving a Sass::SyntaxError whenever I attempt to load a page.

Do you have any idea of what the issue might be?

I have added both `sass` and `sass-rails` gems to my Gemfile and I'm using `rails 4.2.8` and `ruby 2.4.1`

Edit:
I've identified the problem. Commenting out this line in my `config/initializers/assets.rb` solved it
`Rails.application.config.assets.precompile += %w(*.js *.css *.scss *.sass)`

Precompiling stuff apparently fucks it up. Is there any solution to this?

**Comment by miguelsan** [comment]
Try `RAILS_ENV=development rake assets:precompile`.

**Comment by miguelsan** [comment]
Are you sure that it is not a syntax related problem? Bulma's example is SASS, not SCSS (see my [PR](https://github.com/joshuajansen/bulma-rails/pull/30/files)).
