### ISSUE TITLE
 necessary remove width: 100% from table.sass

### ISSUE THREAD

**Issue by askrynnikov** [joshuajansen/bulma-rails#26]
from [bulma-rails/app/assets/stylesheets/sass/elements/table.sass](bulma-rails/app/assets/stylesheets/sass/elements/table.sass]) it is necessary to remove `width: 100%`  

`width: 100%` must be specified with a special modifier `is-fullwidth` see [bulma.io/documentation/elements/table/](https://bulma.io/documentation/elements/table/)

**Comment by joshuajansen** [comment]
Hi @askrynnikov, it seems that this is fixed with Bulma 0.5.1:
https://github.com/joshuajansen/bulma-rails/blob/acf489a786323d22f0fb368cf4a183a84fb4a521/app/assets/stylesheets/sass/elements/table.sass#L86-L87
