### ISSUE TITLE
Github is showing incorrect details regarding the most recent commit

### ISSUE THREAD

**Issue by murdoch** [joshuajansen/bulma-rails#40]
The first screens hot shows that the latest commit was four months ago:

![screenshot_20181101-224923](https://user-images.githubusercontent.com/56636/47884553-1e68a500-de29-11e8-8437-24e8662fd74c.jpeg)

But on closer inspection the latest commit was far more recent:

![screenshot_20181101-224949](https://user-images.githubusercontent.com/56636/47884597-435d1800-de29-11e8-94b5-193245855325.jpeg)

Is there something wrong with github? Or is it me?

**Comment by murdoch** [comment]
I'm in Scotland, in case it's a caching issue.

**Comment by erikdahlstrand** [comment]
Hi @murdoch . I think that is because GitHub shows when the latest commit was committed (July 19), not when it was merged into `master`.

**Comment by murdoch** [comment]
Ahh, you're right, that makes sense. Turns out I've been using github wrong all these years! My bad.
