### ISSUE TITLE
Precompiling assets failed

### ISSUE THREAD

**Issue by pablof300** [joshuajansen/bulma-rails#42]
I am trying to deploy an app using Bulma to Heroku, but I get this error:

    Precompiling assets failed.
    Sass::SyntaxError: File to import not found or unreadable: bulma

**Comment by DerekCrosson** [comment]
@pablof300 did you ever figure this out? I get the same error when deploying to DigitalOcean using Capistrano.

**Comment by DerekCrosson** [comment]
Also can't find where the bulma folder/file is in the project... Also tried renaming ```application.css``` to ```application.scss``` but still have the same error.

**Comment by couchoud** [comment]
@DerekCrosson I ran into the same issue deploying to Heroku. For now, I just installed the bulma npm module through yarn. Install it and put `*= 'bulma/css/bulma.css'` in your `application.css`

**Comment by ndjerrou** [comment]
> @DerekCrosson I ran into the same issue deploying to Heroku. For now, I just installed the bulma npm module through yarn. Install it and put `*= 'bulma/css/bulma.css'` in your `application.css`

Hi,

When I enter `*= 'bulma/css/bulma.css'`,

My application does not load bulma

Any ideas ?

**Comment by couchoud** [comment]
@ndjerrou I had to override some of the default bulma variables in my project and ended up doing an `@import "bulma/bulma"` after the overrides. Maybe give that a try?

**Comment by gd-m** [comment]
I am having the same error. Has anyone found solution to this error?

**Comment by waywho** [comment]
It worked for me if you remove 
` *= require_tree .`
 `*= require_self`
