### ISSUE TITLE
How to import modules

### ISSUE THREAD

**Issue by jrmhaig** [joshuajansen/bulma-rails#43]
Thanks for this gem. What is the correct way to import individual modules rather than the whole of bulma? Would it be possible to add a note to this effect into the `README.rb`?

**Comment by missinglink** [comment]
Works for me:

```scss
// Bulma Base
@import "sass/utilities/_all";

// +Bulma Overrides
@import "overrides";

// Bulma Framework
@import "sass/base/_all";
@import "sass/elements/_all";
@import "sass/form/_all";
@import "sass/components/_all";
@import "sass/grid/_all";
@import "sass/layout/_all";
```

**Comment by Sayantansinharay451** [comment]
`@import "overrides";` what does this does ?

**Comment by missinglink** [comment]
The "overrides" file in the example is where you change builtin variables in Bulma.
When you put your overrides in this location then they are adopted by subsequent code.

For instance you could add:
```css
$primary: rgb(45, 51, 57);
```

Which would change the primary colour of everything in the library.
