### ISSUE TITLE
Update to v0.8.0

### ISSUE THREAD

**Issue by rafaltrojanowski** [joshuajansen/bulma-rails#47]
Thanks for great work! Is there a plan to update to the new version?

**Comment by linyiru** [comment]
@rafaltrojanowski Bulma v0.8.1 is released, fyi: https://github.com/jgthms/bulma/tree/0.8.1

**Comment by fwolfst** [comment]
New versions have been out (and a PR for 0.9 was already published). I think this issue can be closed.
