### ISSUE TITLE
Installed but no bulma file appeared in my asset project folder

### ISSUE THREAD

**Issue by TBrayner** [joshuajansen/bulma-rails#48]
Rails 6.0.2.2
ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]

Gem file:
![image](https://user-images.githubusercontent.com/3511497/79671490-f0079280-81a0-11ea-8b07-71955f2608df.png)

application.scss
![image](https://user-images.githubusercontent.com/3511497/79671531-280ed580-81a1-11ea-9688-85edb5e24497.png)

Bundle installed:
![image](https://user-images.githubusercontent.com/3511497/79671555-60161880-81a1-11ea-8e06-c1c4a1b862b2.png)

Output:
![image](https://user-images.githubusercontent.com/3511497/79671595-c602a000-81a1-11ea-86d0-d5df7701cbe5.png)

**Comment by jcquarto** [comment]
Did this ever get resolved? I have the same issue

**Comment by joelbugarini** [comment]
It looks like the gem copy the bulma files from your `node_modules` folder, so you need to install de npm package before bundling the gem.

`npm install bulma`

then, add the gem

`gem "bulma-rails", "~> 0.9.0"`

`bundle`
