### ISSUE TITLE
installation instructions don't work..

### ISSUE THREAD

**Issue by MaTsou** [joshuajansen/bulma-rails#56]
I followed instructions : 
modify Gemfile and then run bundle..

But bulma-rails get installed in my ~/.rbenv/versions/...  folder and my app/assets/stylesheets/ folder stay as it was before installation.

So what am I  missing ?

Thanks for helping me

**Comment by abepetrillo** [comment]
I know this is old,but you need to make sure `application.css` has been renamed to `application.scss`.
Also in that file, you should have ` @import "bulma";` which I think is in the docs.

**Comment by MaTsou** [comment]
Problem solved. Thanks.

Le samedi 24 décembre 2022 00:03:03 (+01:00), Abraham Petrillo a écrit :



I know this is old,but you need to make sure application.css has been renamed to application.scss.
Also in that file, you should have @import "bulma"; which I think is in the docs.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.


-- 
Message envoyé avec Vivaldi Mail. Téléchargez Vivaldi gratuitement sur vivaldi.com
